config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup' }
  resources :portfolios, except: [:show]
	get 'angular-items', to: 'portfolios#angular'
	get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about', to: "pages#about"
  get 'contact', to: "pages#contact"
  resources :blogs do
		member do
			post :toggle_status
		end
	end
	root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
	belongs_to :topic
	enum status: { draft: 0, published: 1 }
	extend FriendlyId
  friendly_id :title, use: :slugged
	
	validates :title, :body, presence: true
end

app/models/concerns/placeholder.rb
module Placeholder
	extend ActiveSupport::Concern

	def self.image_generator(height:, width:)
		"http://placehold.it/#{height}x#{width}"
	end
end

app/models/guest_user.rb
class GuestUser < User
	attr_accessor :name, :first_name, :last_name, :email
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
	include Placeholder
	validates :title, :body, :main_image, :thumb_image, presence: true
	has_many :technologies
	accepts_nested_attributes_for :technologies, reject_if: lambda { |attr| attr['name'].blank? }

	def self.angular
		where(subtitle: 'Angular')
	end

	scope :ruby_on_rails, -> { where(subtitle: 'Ruby on Rails') }

	after_initialize :set_defaults  # This callback runs after the new action

	def set_defaults
		self.main_image ||= Placeholder.image_generator(height: 600, width: 400) 
		self.thumb_image ||= Placeholder.image_generator(height: 350, width: 200)
	end
end

app/models/skill.rb
class Skill < ApplicationRecord
	include Placeholder
	validates :title, :percent_utilized, presence: true
	after_initialize :set_defaults  # This callback runs after the new action

	def set_defaults
		self.badge ||= Placeholder.image_generator(height: 250, width: 250)
	end
end

app/models/technology.rb
class Technology < ApplicationRecord
  belongs_to :portfolio
end

app/models/topic.rb
class Topic < ApplicationRecord
	has_many :blogs
	validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:site_admin], multiple: false)                                      ##
  ############################################################################################ 
 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	validates :name, presence: true
	
	def first_name
		self.name.split.first	
	end

	def last_name
		self.name.split.last
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
	include DeviseWhitelist
	include SetSource	
	include CurrentUserConcern
	include DefaultPageContent
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]
	layout "blog"
	access all: [:show, :index], user: {except: [:destroy, :new, :create, :edit, :update]}, site_admin: :all

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.order(created_at: :desc)
		@page_title = "My Portfolio Blog"
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
		@page_title = @blog.title
		@seo_keywords = @blog.body
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
    end
  end

	def toggle_status
		@blog.draft? ? @blog.published! : @blog.draft!
		redirect_to blogs_url, notice: "Post status has been updated"
	end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/concerns/current_user_concern.rb
module CurrentUserConcern
	extend ActiveSupport::Concern

	def current_user
		super || guest_user
	end

	def guest_user
		guest = GuestUser.new
		guest.name = "Guest User"
		guest.first_name = "Guest"
		guest.last_name = "User"
		guest.email = "guest@example.com"
		return guest
	end
end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
	extend ActiveSupport::Concern

	included do
		before_filter :configure_permitted_parameters, if: :devise_controller?
	end

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name])	
		devise_parameter_sanitizer.permit(:account_update, keys: [:name])	
	end
end

app/controllers/concerns/set_source.rb
module SetSource
	extend ActiveSupport::Concern

	included do
		before_filter :set_source
	end

	def set_source
		session[:source] = params[:q] if params[:q]
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
		@posts = Blog.all
		@skills = Skill.all
  end

  def about
  end

  def contact
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
	before_action :set_portfolio_item, only: [:show, :edit, :update, :destroy]
	layout "portfolio"
	access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :edit, :update]}, site_admin: :all

	def index
		@portfolio_items = Portfolio.all
	end

	def angular
		@angular_portfolio_items = Portfolio.angular
	end

	def index
		@portfolio_items = Portfolio.all
	end

	def new
		@portfolio_item = Portfolio.new
		3.times { @portfolio_item.technologies.build }
	end

	def create
		@portfolio_item = Portfolio.new(portfolio_params)
		respond_to do |format|
			if @portfolio_item.save
				format.html { redirect_to portfolio_show_path(@portfolio_item), notice: "Portfolio Item created successfully" }
			else
				format.html { render :new }
			end
		end
	end

	def show
	end

	def edit
	end

	def update
		respond_to do |format|
			if @portfolio_item.update(portfolio_params)
				format.html { redirect_to @portfolio_item, notice: "Portfolio Item updated successfully" }
			else
				format.html { render :edit }
			end
		end
	end

	def destroy
		@portfolio_item = Portfolio.find(params[:id])
		@portfolio_item.destroy
		respond_to do |format|
			format.html { redirect_to portfolios_url, notice: "Portfolio Item deleted successfully." }
		end
	end

	private
	def portfolio_params
		params.require(:portfolio).permit(:title, :subtitle, :body, :technologies_attributes => [:name])
	end

	def set_portfolio_item
		@portfolio_item = Portfolio.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def login_helper
		if current_user.is_a? GuestUser
			signup = link_to "Signup", new_user_registration_path
			login = link_to "Login", new_user_session_path
			signup + " | " + login
		else
			link_to "Logout", destroy_user_session_path, method: :delete
		end
	end

	def source_helper(layout_name)
		if session[:source]
			greeting = "Thanks for visiting me from #{session[:source]} and you are on the #{layout_name} layout"
			content_tag(:p, greeting)
		end
	end

	def copyright_generator
		TechienovCopyrightTool::Renderer.copyright "Techienov", "All rights reserved"
	end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<title><%= @page_title %></title>
    <%= csrf_meta_tags %>
		<meta name="keywords" content="<%= @seo_keywords %>">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

		<%= render 'shared/nav', location: 'top' %>

		<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>

		<%= login_helper %>
    <%= yield %>
		<%= source_helper("application") %>
		<%= copyright_generator %>
  </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
		<title><%= @page_title %></title>
    <%= csrf_meta_tags %>
		<meta name="keywords" content="<%= @seo_keywords %>">

    <%= stylesheet_link_tag    'blogs', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
		<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>

		<%= login_helper %>
    <%= yield %>

		<%= render 'shared/nav', location: 'bottom' %>

		<%= source_helper "blog" %>
  </body>
</html>

app/views/layouts/portfolio.html.erb
<!DOCTYPE html>
<html>
  <head>
		<title><%= @page_title %></title>
    <%= csrf_meta_tags %>
		<meta name="keywords" content="<%= @seo_keywords %>">

    <%= stylesheet_link_tag    'portfolios', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
		<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>

		<%= render 'shared/nav', location: 'top' %>

		<%= login_helper %>
    <%= yield %>
		
		<%= source_helper "portfolio" %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p><%= number_to_phone "9876543210" %></p>

app/views/pages/home.html.erb
<div class="site-wrapper">

	<div class="site-wrapper-inner">

		<div class="cover-container">

			<div class="masthead clearfix">
				<div class="inner">
					<h3 class="masthead-brand">Cover</h3>
					<nav class="nav nav-masthead">
						<a class="nav-link active" href="#">Home</a>
						<a class="nav-link" href="#">Features</a>
						<a class="nav-link" href="#">Contact</a>
					</nav>
				</div>
			</div>

			<div class="inner cover">
				<h1 class="cover-heading">Cover your page.</h1>
				<p class="lead">Cover is a one-page template for building simple and beautiful home pages. Download, edit the text, and add your own fullscreen background photo to make it your own.</p>
				<p class="lead">
				<a href="#" class="btn btn-lg btn-secondary">Learn more</a>
				</p>
			</div>

			<div class="mastfoot">
				<div class="inner">
					<p>Cover template for <a href="https://getbootstrap.com">Bootstrap</a>, by <a href="https://twitter.com/mdo">@mdo</a>.</p>
				</div>
			</div>

		</div>

	</div>

</div>

app/views/shared/_nav.html.erb
<div class="<%= location %>">
	<div><%= link_to "Home", root_path %></div>
	<div><%= link_to "About", about_path %></div>
	<div><%= link_to "Contact", contact_path %></div>
	<div><%= link_to "Blog", blogs_path %></div>
	<div><%= link_to "Portfolio", portfolios_path %></div>
</div>